services:
  - type: web
    name: robofix-backend
    runtime: docker
    dockerfilePath: deployment/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
